import { initDb, getDb } from './database';
import { seedDefaultBudgets } from '../adapters/mock-budget';
import { ingestTransactions } from '../services/ingestion';
import { detectRecurringCandidates, upsertRecurringCandidates } from '../services/subscription-analysis';
import { buildSeedTransactionsForUser } from '../services/nessie';
import { createAdapters } from '../adapters';
import { AgentRunner, DedalusProvider, ClaudeLLMProvider, MockLLMProvider, LLMProvider } from '../agents/runner';
import { Orchestrator } from '../orchestrator';
import path from 'path';
import fs from 'fs';

const dataDir = path.join(__dirname, '../../data');
if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

function getLLMProvider(): LLMProvider {
  let dedalusKey = process.env.DEDALUS_API_KEY || '';
  let anthropicKey = process.env.ANTHROPIC_API_KEY || '';

  // Also check config.local.ts if it exists (matches index.ts behavior)
  try {
    const configModule = require('../../config.local');
    dedalusKey = dedalusKey || configModule.CONFIG?.dedalus?.apiKey || '';
    anthropicKey = anthropicKey || configModule.CONFIG?.anthropic?.apiKey || '';
  } catch {
    // No config.local.ts — using .env or environment variables
  }

  if (dedalusKey && dedalusKey !== 'your-dedalus-api-key-here') {
    return new DedalusProvider(dedalusKey);
  }
  if (anthropicKey) {
    return new ClaudeLLMProvider(anthropicKey);
  }
  return new MockLLMProvider();
}

async function main() {
  console.log('Seeding database...');
  initDb();
  const db = getDb();

  // Create demo user
  const userId = 'user_1';
  db.prepare(`
    INSERT OR IGNORE INTO user_profile (id, timezone, preferences)
    VALUES (?, 'America/New_York', '{"quest_types_avoid": [], "notification_limit": 5}')
  `).run(userId);

  // Create scotty state
  db.prepare(`
    INSERT OR IGNORE INTO scotty_state (user_id, happiness, mood, food_credits)
    VALUES (?, 70, 'content', 10)
  `).run(userId);

  // Seed budgets
  seedDefaultBudgets(userId);

  // Seed transactions from JSON file (generated by `npx tsx src/db/generate-seed-data.ts`)
  db.prepare(`DELETE FROM transaction_ WHERE user_id = ?`).run(userId);
  const txns = buildSeedTransactionsForUser(userId);
  const result = ingestTransactions(txns);
  console.log(`Inserted ${result.inserted} transactions`);

  // Detect and persist recurring candidates
  const candidates = detectRecurringCandidates(userId);
  upsertRecurringCandidates(candidates);
  console.log(`Detected ${candidates.length} recurring candidates`);

  // Clear stale data so daily digest runs fresh (delete children before parents for FK)
  db.prepare(`DELETE FROM quest_progress_snapshot WHERE quest_id IN (SELECT id FROM quest WHERE user_id = ?)`).run(userId);
  db.prepare(`DELETE FROM quest WHERE user_id = ?`).run(userId);
  db.prepare(`DELETE FROM insight WHERE user_id = ?`).run(userId);
  db.prepare(`DELETE FROM action_queue_item WHERE user_id = ?`).run(userId);
  db.prepare(`DELETE FROM idempotency_key WHERE key LIKE ?`).run(`%${userId}%`);

  // Run daily digest to generate quests + insights
  console.log('Running daily digest to generate quests and insights...');
  const llm = getLLMProvider();
  const adapters = createAdapters();
  const runner = new AgentRunner({ adapters, llmProvider: llm });
  const orchestrator = new Orchestrator(adapters, runner);

  try {
    const digestResult = await orchestrator.runDailyDigest(userId);
    console.log(`Daily digest complete (${digestResult.idempotencyKey})`);

    // Show generated quests
    const quests = db.prepare(
      `SELECT title, metric_type, reward_food_type FROM quest WHERE user_id = ? ORDER BY created_at DESC LIMIT 5`
    ).all(userId) as any[];
    if (quests.length > 0) {
      console.log(`Generated ${quests.length} quest(s):`);
      quests.forEach((q: any) => console.log(`  - ${q.title} (${q.metric_type}, reward: ${q.reward_food_type})`));
    }

    // Show generated insights
    const insights = db.prepare(
      `SELECT title, blurb FROM insight WHERE user_id = ? ORDER BY created_at DESC LIMIT 3`
    ).all(userId) as any[];
    if (insights.length > 0) {
      console.log(`Generated ${insights.length} insight(s):`);
      insights.forEach((i: any) => console.log(`  - ${i.title}: ${i.blurb.substring(0, 80)}...`));
    }
  } catch (err: any) {
    console.warn(`Daily digest failed (non-fatal): ${err.message}`);
  }

  console.log('Seed complete. Demo user:', userId);
}

main().catch(err => {
  console.error('Seed failed:', err);
  process.exit(1);
});
